"""Add relationship between Video and Users

Revision ID: ce2dff7ba17c
Revises: 94436e424437
Create Date: 2023-12-04 21:59:28.554435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce2dff7ba17c'
down_revision: Union[str, None] = '94436e424437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'video', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='foreignkey')
    op.drop_column('video', 'owner_id')
    # ### end Alembic commands ###
